### ISSUE TITLE
Allow a user to lease a cluster by name

### ISSUE THREAD

**Issue by jchauncey** [deis/k8s-claimer#71]
Would be useful for testing different configurations.

**Comment by arschles** [comment]
I think that adding tags to each cluster would be more helpful here, so that we can lease a cluster across multiple dimensions (i.e. the memory & CPU configuration of the target cluster).

Alternatively, if the "query" on cluster is only going to be based on the compute, storage and network resources, we might be able to get those from the GKE API and just query on those attributes.

Thoughts?
